

/*****************************************************************
 * 						Generated by Xpand Eclipse
 *						File :	app_config.c
 *						Date : 
 *						Author : Matthieu Kowalewski
 *						License : GPLv2
 ****************************************************************/
#include "os_task.h"
#include "os_appmode.h"
#include "os_os.h"
#include "app/app_isr.h"



#define app1_bit  (1 << app1_ID)

struct OsAppMode app1_OsAppMode = {
	"app1",		//	EcucStringParamDef OsAppModeName;
	app1_bit	//	EcucIntegerParamDef OsAppModeValue;	
};

struct OsAppMode * OsAppMode_table[APP_COUNT] = {
	&app1_OsAppMode,
};

/*********************** Resource OsResource1 ***********************/
struct OsResource OsResource1_OsResource = {
		RESOURCE_STANDARD,	//OsResourceProperty OsResourceProperty;	
		//		//struct OsApplication * OsApplicationAccessingApplication;
		NULL,	//struct OsResource * OsResourceLinkedResourceRef;	
		NULL		//struct OsResourceXenomai * OsResourceXenomai;		/*!< Xenomai implementation for a Resource */};
};

struct OsResource * OsResource_table[RESOURCE_COUNT] = {
	&OsResource1_OsResource,
};

/*********************** Task OsTask3 ***********************/
extern void OsTask3_function(void);


struct OsTask OsTask3_OsTask = {
	1,	//	EcucIntegerParamDef OsTaskActivation;
	80,		//	EcucIntegerParamDef OsTaskPriority;
	TASK_NON,	//	EcucEnumerationParamDef OsTaskSchedule; NON or FULL preempt
	//											//	struct OsApplication * OsTaskAccessingApplication;
	//											//	struct OsEvent * OsTaskEventRef;
	NULL,										//	struct OsResource ** OsTaskResourceRef;
	NULL,										//	struct OsTaskAutostart * OsTaskAutostart;
	//											//	struct OsTaskTimingProtection * OsTaskTimingProtection;
	OsTask3_function,			//	EcucFunctionNameDef handler;
	OsTask3_RESOURCE_COUNT,	//	EcucIntegerParamDef ResourceCount;	
	NULL										//	struct OsTaskXenomai * OsTaskXenomai;
};


/*********************** Task OsTask2 ***********************/
extern void OsTask2_function(void);
struct OsResource * OsTask2_OsTaskResourceRef[OsTask2_RESOURCE_COUNT] = {
	&OsResource1_OsResource,
};


struct OsTask OsTask2_OsTask = {
	1,	//	EcucIntegerParamDef OsTaskActivation;
	100,		//	EcucIntegerParamDef OsTaskPriority;
	TASK_NON,	//	EcucEnumerationParamDef OsTaskSchedule; NON or FULL preempt
	//											//	struct OsApplication * OsTaskAccessingApplication;
	//											//	struct OsEvent * OsTaskEventRef;
	OsTask2_OsTaskResourceRef,	//	struct OsResource ** OsTaskResourceRef;	
	NULL,										//	struct OsTaskAutostart * OsTaskAutostart;
	//											//	struct OsTaskTimingProtection * OsTaskTimingProtection;
	OsTask2_function,			//	EcucFunctionNameDef handler;
	OsTask2_RESOURCE_COUNT,	//	EcucIntegerParamDef ResourceCount;	
	NULL										//	struct OsTaskXenomai * OsTaskXenomai;
};


/*********************** Task OsTask1 ***********************/
extern void OsTask1_function(void);
struct OsResource * OsTask1_OsTaskResourceRef[OsTask1_RESOURCE_COUNT] = {
	&OsResource1_OsResource,
};


struct OsTask OsTask1_OsTask = {
	1,	//	EcucIntegerParamDef OsTaskActivation;
	80,		//	EcucIntegerParamDef OsTaskPriority;
	TASK_NON,	//	EcucEnumerationParamDef OsTaskSchedule; NON or FULL preempt
	//											//	struct OsApplication * OsTaskAccessingApplication;
	//											//	struct OsEvent * OsTaskEventRef;
	OsTask1_OsTaskResourceRef,	//	struct OsResource ** OsTaskResourceRef;	
	NULL,										//	struct OsTaskAutostart * OsTaskAutostart;
	//											//	struct OsTaskTimingProtection * OsTaskTimingProtection;
	OsTask1_function,			//	EcucFunctionNameDef handler;
	OsTask1_RESOURCE_COUNT,	//	EcucIntegerParamDef ResourceCount;	
	NULL										//	struct OsTaskXenomai * OsTaskXenomai;
};


 
struct OsTask * OsTask_table[TASK_COUNT] = {
&OsTask3_OsTask, 
&OsTask2_OsTask, 
&OsTask1_OsTask, 
};

/*********************** Counter counter1 ***********************/
struct OsCounter counter1_OsCounter = {
	32000,		//	EcucIntegerParamDef OsCounterMaxAllowedValue;
	1,		//	EcucIntegerParamDef OsCounterMinCycle;
	1,		//	EcucIntegerParamDef OsCounterTicksPerBase;
	COUNTER_HARDWARE,	//	OsCounterType OsCounterType;
	0.001,		//	EcucFloatParamDef OsSecondsPerTick;
	//		//	struct OsApplication * OsCounterAccessingApplication;
	//		//	struct OsDriver * OsDriver;
	//		//	struct OsTimerConstant * OsTimerConstant;
	NULL	//	IMPL+ : struct OsCounterXenomai * OsCounterXenomai;
};
 
struct OsCounter * OsCounter_table[COUNTER_COUNT] = {
&counter1_OsCounter,
};

/*********************** Alarm alarm1 ***********************/
struct OsAlarmAutostart alarm1_OsAlarmAutostart = {
	1000, 								//uint64 OsAlarmAlarmTime; 		/*!< Start time of the alarm int tick */
	ALARM_ABSOLUTE,										//OsAlarmAutostartType OsAlarmAutostartType;	/*!< Alarm type : OsAlarmAutostartType */
	0, 								//uint64 OsAlarmCycleTime;		/*!< Cycle time of the alarm in tick */
	&app1_OsAppMode		//struct OsAppMode * OsAlarmAppModeRef;		/*!< Appmode to autostart the alarm */
};


struct OsAlarmActivateTask alarm1_OsAlarmActivateTask = {
	&OsTask1_OsTask			// struct OsTask * OsAlarmActivateTaskRef; /*!< Task to activate */
}; 


struct OsAlarmAction  alarm1_OsAlarmAction = {
	&alarm1_OsAlarmActivateTask,
	NULL,
	NULL
};

struct OsAlarm alarm1_OsAlarm = {
	//					//	struct OsApplication * OsAlarmAccesingApplication;
	&counter1_OsCounter,		//	struct OsCounter * OsAlarmCounterRef;
	&alarm1_OsAlarmAction,		//	struct OsAlarmAction * OsAlarmAction;
	&alarm1_OsAlarmAutostart,
	NULL				//	IMPL+ :  struct OsAlarmXenomai * OsAlarmXenomai;
};
 
struct OsAlarm* OsAlarm_table[ALARM_COUNT] = {
&alarm1_OsAlarm,
};

//extern  struct OsIsr* OsIsr_table[ISR_COUNT_MANUEL];
struct OsIsr* OsIsr_table[ISR_COUNT] = {
};
struct Os os = {
	OsAlarm_table,	// 	struct OsAlarm ** OsAlarm;
	OsAppMode_table,//	struct OsAppMode ** OsAppMode;
	//	NULL,		//	struct OsApplication ** OsApplication;
	OsCounter_table,//	struct OsCounter ** OsCounter;
	//	NULL,		//	struct OsEvent ** OsEvent;
	//	NULL,		//	struct OsIoc * OsIoc;
	OsIsr_table,		//	struct OsIsr ** OsIsr;
	OsResource_table,			//	struct OsResource ** OsResource;
	//	NULL,		//	struct OsScheduleTable ** OsScheduleTable;
	//	NULL,		//	struct OsSpinlock * OsSpinlock;
	OsTask_table	// 	struct OsTask * OsTask;
};


